# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/

# deploy_development:
#   type: deploy
#   environment:
#     name: development
#     url: api.quickplay.app
#   script:
#     - ssh $SERVER_USER@$SERVER_HOST "cd /data1/opt/emtiv-backend && sudo git pull origin development-mobile-api && sudo pm2 reload all && exit"
#   only:
#     - development-mobile-api

stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: development
    url: api.quickplay.app
  before_script:  
      - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
      - 'which sshpass || ( apt-get update -y && apt-get install sshpass -y )'
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
      - chmod 700 ~/.ssh/id_rsa
      - eval $(ssh-agent -s)
      - ssh-add ~/.ssh/id_rsa
      - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
      - ssh-keyscan gitlab.com | sort -u - ~/.ssh/known_hosts -o ~/.ssh/known_hosts
      - rm -rf .git
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - sshpass -p "$SERVER_PASSWORD" ssh -p 40000 administrator@103.253.113.215 "cd /data1/opt/emtiv-backend && sudo git pull origin development-mobile-api && sudo pm2 reload all && exit"
    # - ssh -vvv administrator@103.253.113.215 -p 40000 "Quickplay1! && cd /data1/opt/emtiv-backend && sudo git pull origin development-mobile-api && sudo pm2 reload all && exit"
  only:
    - development-mobile-api