module.exports = {
    HARMFUL_ACTS: 'HARMFUL_ACTS',
    NO_COACH: 'NO_COACH',
    WRONG_ADDRESS: 'WRONG_ADDRESS',
    PLACE_UNAVAILABLE: 'PLACE_UNAVAILABLE',
    WRONG_ATTENDANCE: 'WRONG_ATTENDANCE',
}