module.exports = {
    ORGANIZATION: 'Company',
    BRANCH: 'Branch',
    DEPARTMENT: 'Department',
    GRADE: 'Position',
    USER: 'Employee',
    ABSENCE: 'Absence',
    ATTENDANCE: 'Attendance',
    SHIFT: 'Shift',
    TIMESHEET: 'Timesheet',
    PROJECT: 'Project',
    ANNOUNCEMENT: 'Announcement',
    REPORT: 'Report',
    SETTING: 'Setting',
    CLASS: 'Class',
    TEAM: 'Team',
    FORUM: 'Forum',
    NEWS: 'News',
    TOURNAMENT: 'Tournament'
}