exports.seed = (knex, Promise) => knex('eclass').del()
    .then(() =>
        knex('eclass').insert(
            [
                // {
                //     eclassname: "Class A",
                //     eclassstartdate: 1599573209615,
                //     eclassenddate: 1599673209615,
                //     eclasstype: "PUBLIC",
                //     eclassprice: 15000,
                //     eclassaddress: "Banten",
                //     eclassdescription: "Deskripsi Class A",
                //     eclasspicname: "Steven",
                //     eclasspicmobilenumber: "08123123123",
                //     eindustryeindustryid: 1,
                //     ecompanyecompanyid: 6,
                //     efileefileid: 1,
                //     eclasscreatetime: Date.now(),
                //     eclasscreateby: 0
                // },
                // {
                //     eclassname: "Class B",
                //     eclassstartdate: 1599573209615,
                //     eclassenddate: 1599673209615,
                //     eclasstype: "PRIVATE",
                //     eclassprice: 31000,
                //     eclassaddress: "Banten",
                //     eclassdescription: "Deskripsi Class B",
                //     eclasspicname: "Steven",
                //     eclasspicmobilenumber: "08123123123",
                //     eindustryeindustryid: 1,
                //     ecompanyecompanyid: 6,
                //     efileefileid: 1,
                //     eclasscreatetime: Date.now(),
                //     eclasscreateby: 0
                // },
                {
                    eclassname: "Lisensi C",
                    eclassstartdate: null,
                    eclassenddate: null,
                    eclasstype: "PUBLIC",
                    eclassprice: null,
                    eclassaddress: "Kalimantan Selatan, Kalimantan Selatan",
                    eclassdescription: "",
                    eclasspicname: "Baktiansyah",
                    eclasspicmobilenumber: "+62 813-5100-6386",
                    eindustryeindustryid: 1,
                    ecompanyecompanyid: 6,
                    efileefileid: null,
                    eclasscreatetime: Date.now(),
                    eclasscreateby: 0
                },
                {
                    eclassname: "Lisensi C",
                    eclassstartdate: null,
                    eclassenddate: null,
                    eclasstype: "PUBLIC",
                    eclassprice: null,
                    eclassaddress: "Jawa Barat, Bandung",
                    eclassdescription: "",
                    eclasspicname: "Alex",
                    eclasspicmobilenumber: "+62 821-1911-6663",
                    eindustryeindustryid: 1,
                    ecompanyecompanyid: 6,
                    efileefileid: null,
                    eclasscreatetime: Date.now(),
                    eclasscreateby: 0
                },
                {
                    eclassname: "Lisensi C",
                    eclassstartdate: null,
                    eclassenddate: null,
                    eclasstype: "PUBLIC",
                    eclassprice: null,
                    eclassaddress: "DKI Jakarta, Persija Academy Pulomas",
                    eclassdescription: "",
                    eclasspicname: "Zaenal Abidin",
                    eclasspicmobilenumber: "+62 812-8035-480",
                    eindustryeindustryid: 1,
                    ecompanyecompanyid: 6,
                    efileefileid: null,
                    eclasscreatetime: Date.now(),
                    eclasscreateby: 0
                },
                {
                    eclassname: "Lisensi C",
                    eclassstartdate: null,
                    eclassenddate: null,
                    eclasstype: "PUBLIC",
                    eclassprice: null,
                    eclassaddress: "Bali, Bali",
                    eclassdescription: "",
                    eclasspicname: "Nasser",
                    eclasspicmobilenumber: "+62 812-3628-6219",
                    eindustryeindustryid: 1,
                    ecompanyecompanyid: 6,
                    efileefileid: null,
                    eclasscreatetime: Date.now(),
                    eclasscreateby: 0
                },
                {
                    eclassname: "Lisensi C",
                    eclassstartdate: null,
                    eclassenddate: null,
                    eclasstype: "PUBLIC",
                    eclassprice: null,
                    eclassaddress: "Sumatera Barat, Padang",
                    eclassdescription: "",
                    eclasspicname: "Dede",
                    eclasspicmobilenumber: "+62 813-7454-1888",
                    eindustryeindustryid: 1,
                    ecompanyecompanyid: 6,
                    efileefileid: null,
                    eclasscreatetime: Date.now(),
                    eclasscreateby: 0
                },
                // 6
                {
                    eclassname: "Lisensi D",
                    eclassstartdate: null,
                    eclassenddate: null,
                    eclasstype: "PUBLIC",
                    eclassprice: null,
                    eclassaddress: "Kalimantan Timur, Penajam Paser Utara",
                    eclassdescription: "",
                    eclasspicname: "Idam",
                    eclasspicmobilenumber: "+62 812-2497-4590",
                    eindustryeindustryid: 1,
                    ecompanyecompanyid: 6,
                    efileefileid: null,
                    eclasscreatetime: Date.now(),
                    eclasscreateby: 0
                },
                {
                    eclassname: "Lisensi D",
                    eclassstartdate: null,
                    eclassenddate: null,
                    eclasstype: "PUBLIC",
                    eclassprice: null,
                    eclassaddress: "Maluku Utara, Ternate",
                    eclassdescription: "",
                    eclasspicname: "Bahrul Ulum",
                    eclasspicmobilenumber: "+62 821-8884-3282",
                    eindustryeindustryid: 1,
                    ecompanyecompanyid: 6,
                    efileefileid: null,
                    eclasscreatetime: Date.now(),
                    eclasscreateby: 0
                },
                {
                    eclassname: "Lisensi D",
                    eclassstartdate: null,
                    eclassenddate: null,
                    eclasstype: "PUBLIC",
                    eclassprice: null,
                    eclassaddress: "DKI Jakarta, D'Arcici",
                    eclassdescription: "",
                    eclasspicname: "Zaenal Abidin",
                    eclasspicmobilenumber: "+62 812-8035-480",
                    eindustryeindustryid: 1,
                    ecompanyecompanyid: 6,
                    efileefileid: null,
                    eclasscreatetime: Date.now(),
                    eclasscreateby: 0
                },
                {
                    eclassname: "Lisensi D",
                    eclassstartdate: null,
                    eclassenddate: null,
                    eclasstype: "PUBLIC",
                    eclassprice: null,
                    eclassaddress: "Sulawesi Selatan, Bone",
                    eclassdescription: "",
                    eclasspicname: "Hariyanto",
                    eclasspicmobilenumber: "+62 812-4582-4020",
                    eindustryeindustryid: 1,
                    ecompanyecompanyid: 6,
                    efileefileid: null,
                    eclasscreatetime: Date.now(),
                    eclasscreateby: 0
                },
                {
                    eclassname: "Lisensi D",
                    eclassstartdate: null,
                    eclassenddate: null,
                    eclasstype: "PUBLIC",
                    eclassprice: null,
                    eclassaddress: "Jawa Tengah, Surakarta",
                    eclassdescription: "",
                    eclasspicname: "Slamet",
                    eclasspicmobilenumber: "+62 812-2150-3300",
                    eindustryeindustryid: 1,
                    ecompanyecompanyid: 6,
                    efileefileid: null,
                    eclasscreatetime: Date.now(),
                    eclasscreateby: 0
                },
                // 11
                {
                    eclassname: "Lisensi D",
                    eclassstartdate: null,
                    eclassenddate: null,
                    eclasstype: "PUBLIC",
                    eclassprice: null,
                    eclassaddress: "Bangka Belitung, Babel",
                    eclassdescription: "",
                    eclasspicname: "Yopie Riwoe",
                    eclasspicmobilenumber: "",
                    eindustryeindustryid: 1,
                    ecompanyecompanyid: 6,
                    efileefileid: null,
                    eclasscreatetime: Date.now(),
                    eclasscreateby: 0
                },
                {
                    eclassname: "Lisensi D",
                    eclassstartdate: null,
                    eclassenddate: null,
                    eclasstype: "PUBLIC",
                    eclassprice: null,
                    eclassaddress: "Sulawesi Selatan, Sinjai",
                    eclassdescription: "",
                    eclasspicname: "Hariyanto",
                    eclasspicmobilenumber: "+62 812-4582-4020",
                    eindustryeindustryid: 1,
                    ecompanyecompanyid: 6,
                    efileefileid: null,
                    eclasscreatetime: Date.now(),
                    eclasscreateby: 0
                },
                {
                    eclassname: "Lisensi D",
                    eclassstartdate: null,
                    eclassenddate: null,
                    eclasstype: "PUBLIC",
                    eclassprice: null,
                    eclassaddress: "Jawa Tengah, Kudus",
                    eclassdescription: "",
                    eclasspicname: "Slamet",
                    eclasspicmobilenumber: "+62 812-2150-3300",
                    eindustryeindustryid: 1,
                    ecompanyecompanyid: 6,
                    efileefileid: null,
                    eclasscreatetime: Date.now(),
                    eclasscreateby: 0
                },
                {
                    eclassname: "Lisensi D",
                    eclassstartdate: null,
                    eclassenddate: null,
                    eclasstype: "PUBLIC",
                    eclassprice: null,
                    eclassaddress: "Jawa Tengah, Semarang",
                    eclassdescription: "",
                    eclasspicname: "Slamet",
                    eclasspicmobilenumber: "+62 812-2150-3300",
                    eindustryeindustryid: 1,
                    ecompanyecompanyid: 6,
                    efileefileid: null,
                    eclasscreatetime: Date.now(),
                    eclasscreateby: 0
                },
                {
                    eclassname: "Lisensi D",
                    eclassstartdate: null,
                    eclassenddate: null,
                    eclasstype: "PUBLIC",
                    eclassprice: null,
                    eclassaddress: "Bali, Tabanan",
                    eclassdescription: "",
                    eclasspicname: "Nasser",
                    eclasspicmobilenumber: "+62 812-3628-6219",
                    eindustryeindustryid: 1,
                    ecompanyecompanyid: 6,
                    efileefileid: null,
                    eclasscreatetime: Date.now(),
                    eclasscreateby: 0
                }
            ]
        ));
